# Generated by Django 4.2.30 on 2026-04-23 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNS", "Unstarted"),
                            ("INP", "In Progress"),
                            ("FIN", "Finished"),
                        ],
                        default="UNS",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Name or link")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.CharField(blank=True, help_text="Author", max_length=50),
                ),
                (
                    "preferred_format",
                    models.CharField(
                        blank=True,
                        help_text="Preferred format, e.g. paperback, audiobook, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "recommender",
                    models.CharField(
                        blank=True,
                        help_text="Person, institution, website, or tweet that recommended the learning resource to you",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="File path, URL, bookshop name, or library",
                        max_length=250,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="e.g. why the recommender recommended it, you added it, what it covers, details such as price, or even what you are learning from this resource!",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lrt.category"
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lrt.resourcetype",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default="UNS",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lrt.status",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, null=True, to="lrt.tag")),
            ],
            options={
                "verbose_name_plural": "entries",
            },
        ),
    ]
